### ISSUE TITLE
Doesn't work on the latest version 1.0.1-a.8

### ISSUE THREAD

**Issue by umarhamzy** [mally8/zen-browser-no-sidebar-scrollbar#1]
Unfortunately, the scroll mod doesn't work with the latest version mentioned in the title.

**Comment by mally8** [comment]
Should be fixed when PR gets merged, Thanks!

**Comment by umarhamzy** [comment]
Of course!

**Comment by mally8** [comment]
It is merged now 😊

**Comment by umarhamzy** [comment]
Sickkk!
