### ISSUE TITLE
Request: Hide Pinned Tabs Scrollbar (Zen Browser v1.0.1-a.18)

### ISSUE THREAD

**Issue by KiKaraage** [mally8/zen-browser-no-sidebar-scrollbar#2]
![image](https://github.com/user-attachments/assets/7eb49031-1678-4bdd-80d2-6349dde83090)

Hope this scrollbar can be hidden too!

**Comment by mally8** [comment]
Waiting for merge. Thanks! 😊

**Comment by mally8** [comment]
It's merged now.
