### ISSUE TITLE
Doesn't work on latest version 1.0.2-b.2

### ISSUE THREAD

**Issue by ekarious** [mally8/zen-browser-no-sidebar-scrollbar#3]
It seems the scroll doesn't work again

**Comment by mally8** [comment]
Which layout are you using ?
I'm on b.2 and it seems to be working fine on all layouts.

**Comment by ekarious** [comment]
I'm using the "Multiple Toolbar" layout and I am on windows 10.

**Comment by mally8** [comment]
No idea, still can't reproduce the issue.
Check if the mod is enabled or updated and if that still doesn't fix it then I would love a video showing the mod is enabled and it not working.

**Comment by Car0lina5** [comment]
Hello! It's not working for me either. I've already restarted the browser. I tried uninstalling the mod and installing it again but unfortunately without success. It seems like it started after the last update.

https://github.com/user-attachments/assets/0351b245-240d-41f2-8adc-e88e59e15467

**Comment by mally8** [comment]
That's the Resize bar for changing the Toolbar's width not to be confused with Scrollbar that appears when there are too many tabs which you can see in the picture below 😅
![image](https://github.com/user-attachments/assets/47d52635-46e8-4e2a-8f24-837c2b885838)
It's not really the scope of this mod, someone can make a mod for that if its possible!

If that's what you mean @ekarious too then I would appreciate you closing the issue.

**Comment by Car0lina5** [comment]
Got it, thanks for the clarification. I hadn't really noticed that before so I thought the mod took care of that too 😅

**Comment by ekarious** [comment]
Sorry, it seems I got confused as well. It is working fine :)
